services:
  mysql-sentiment:
    container_name: mysql-sentiment
    image: mysql
    environment:
      MYSQL_HOST: '%'
      MYSQL_ROOT_PASSWORD: sentiment
      MYSQL_DATABASE: sentiment_data
      MYSQL_USER: sentiment
      MYSQL_PASSWORD: sentiment
      MYSQL_TCP_PORT: 3311
    ports:
      - "3311:3311"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    networks:
      sentiment-net:
  sentiment-service:
    container_name: sentiment-service
    image: ngoxuanchien/sentiment-service
    depends_on:
      mysql-sentiment:
        condition: service_healthy
    environment:
      SPRING_R2DBC_SERVER: mysql-sentiment
      SPRING_R2DBC_PORT: 3311
      SPRING_R2DBC_NAME: sentiment_data
      SPRING_R2DBC_USERNAME: sentiment
      SPRING_R2DBC_PASSWORD: sentiment
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    restart: always
    networks:
      sentiment-net:
  sentiment-analysis:
    container_name: sentiment-analysis
    image: ngoxuanchien/sentiment-analysis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    restart: always
    networks:
      sentiment-net:
networks:
  sentiment-net:
    name: sentiment-net